import { Uri, WorkspaceFolder } from "vscode";
import { JobLogInfo } from "./jobLog";
import { IProjectT } from "./iProjectT";
import { LibraryType } from "./views/projectExplorer/library";
import { IBMiJsonT } from "./ibmiJsonT";
import { IBMiObject } from "@halcyontech/vscode-ibmi-types";
import { ValidatorResult } from "jsonschema";
export type ProjectFileType = 'iproj.json' | '.ibmi.json' | 'joblog.json' | 'output.log' | '.env';
export type LibraryList = {
    libraryInfo: IBMiObject;
    libraryType: string;
}[];
export type EnvironmentVariables = {
    [name: string]: string;
};
export type Direction = 'up' | 'down';
export type Position = 'first' | 'last' | 'middle';
export declare class IProject {
    workspaceFolder: WorkspaceFolder;
    private name;
    private state;
    private buildMap;
    private libraryList;
    private jobLogs;
    private environmentValues;
    private validatorResult;
    constructor(workspaceFolder: WorkspaceFolder);
    getName(): string;
    getProjectFileUri(type: ProjectFileType, directory?: Uri): Uri;
    projectFileExists(type: ProjectFileType, directory?: Uri): Promise<boolean>;
    resolveVariable(lib: string, values: EnvironmentVariables): string;
    getState(): Promise<IProjectT | undefined>;
    updateState(): Promise<void>;
    setState(state: IProjectT | undefined): void;
    getUnresolvedState(): Promise<IProjectT | undefined>;
    getBuildMap(): Promise<Map<string, IBMiJsonT> | undefined>;
    updateBuildMap(): Promise<void>;
    setBuildMap(buildMap: Map<string, IBMiJsonT> | undefined): void;
    getUnresolvedIBMiJson(directory: Uri): Promise<IBMiJsonT | undefined>;
    getIBMiJson(ibmiJsonUri: Uri, buildMap?: Map<string, IBMiJsonT>, resolvedIBMiJson?: IBMiJsonT): Promise<IBMiJsonT | undefined>;
    private searchParentIBMiJson;
    addToIncludePaths(directoryToAdd: string): Promise<void>;
    configureAsVariable(attributes: (keyof IProjectT)[], variable: string, value: string): Promise<void>;
    removeFromIncludePaths(directoryToRemove: string): Promise<void>;
    moveIncludePath(pathToMove: string, direction: Direction): Promise<void>;
    setAsTargetLibraryForCompiles(library: string): Promise<void>;
    setTargetLibraryForCompiles(library: string, variable: string, directory: Uri): Promise<void>;
    setTargetCCSIDForCompiles(tgtCcsid: string, directory: Uri): Promise<void>;
    getLibraryList(): Promise<LibraryList | undefined>;
    updateLibraryList(): Promise<void>;
    setLibraryList(libraryList: LibraryList | undefined): void;
    addToLibraryList(library: string, position: 'preUsrlibl' | 'postUsrlibl'): Promise<void>;
    setCurrentLibrary(library: string): Promise<void>;
    removeFromLibraryList(library: string, type: LibraryType): Promise<void>;
    moveLibrary(library: string, type: LibraryType, direction: Direction): Promise<void>;
    createIProj(description: string): Promise<boolean>;
    updateIProj(iProject: IProjectT): Promise<boolean>;
    updateIBMiJson(ibmiJson: IBMiJsonT, directory: Uri): Promise<boolean>;
    createEnv(): Promise<boolean>;
    getEnv(): Promise<EnvironmentVariables>;
    updateEnv(variable: string, value: string): Promise<void>;
    getValidatorResult(): ValidatorResult;
    getVariables(): Promise<string[]>;
    getObjectLibraries(): Promise<Map<string, LibraryType[]> | undefined>;
    getDeployDir(): string | undefined;
    getDefaultDeployLocation(): string;
    getJobLogs(): JobLogInfo[];
    readJobLog(): Promise<void>;
    clearJobLogs(): Promise<void>;
    static validateJobLog(content: string): JobLogInfo;
}
